In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC 
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
digits = load_digits()

In [2]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(digits.data,digits.target,test_size=0.3)

In [3]:
lr = LogisticRegression()
lr.fit(x_train, y_train)
lr.score(x_test,y_test)

C:\Users\susdh\anaconda3\envs\env1\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9685185185185186

In [4]:
svm = SVC()
svm.fit(x_train, y_train)
svm.score(x_test, y_test)

0.9851851851851852

In [5]:
rf = RandomForestClassifier(n_estimators=40)
rf.fit(x_train, y_train)
rf.score(x_test,y_test)

0.975925925925926

In [12]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [13]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [14]:
def get_score(model,x_train,x_test,y_train,y_test):
    model.fit(x_train,y_train)
    return model.score(x_test,y_test)

In [15]:
get_score(LogisticRegression(),x_train,x_test,y_train,y_test)

C:\Users\susdh\anaconda3\envs\env1\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9685185185185186

In [17]:
get_score(SVC(),x_train,x_test,y_train,y_test)

0.9851851851851852

In [18]:
get_score(RandomForestClassifier(n_estimators=40),x_train,x_test,y_train,y_test)

0.975925925925926

In [19]:
from sklearn.model_selection import StratifiedGroupKFold
folds = StratifiedGroupKFold(n_splits=3)

In [25]:
score_l =  []
score_svm = []
score_rf = []
for train_index, test_index in kf.split(digits.data):
    x_train, x_test, y_train, y_test = digits.data[train_index],digits.data[test_index],\
                                       digits.target[train_index], digits.target[test_index]
    score_l.append(get_score(LogisticRegression(),x_train,x_test, y_train, y_test))
    score_svm.append(get_score(SVC(),x_train,x_test, y_train, y_test))
    score_rf.append(get_score(RandomForestClassifier(),x_train,x_test, y_train, y_test))

C:\Users\susdh\anaconda3\envs\env1\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\susdh\anaconda3\envs\env1\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-

In [26]:
score_rf

[0.9348914858096828, 0.9565943238731218, 0.9215358931552587]

In [27]:
score_svm

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [28]:
score_l

[0.9232053422370617, 0.9415692821368948, 0.9148580968280468]

In [29]:
from sklearn.model_selection import cross_val_score

In [30]:
cross_val_score(LogisticRegression(), digits.data, digits.target)

C:\Users\susdh\anaconda3\envs\env1\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\susdh\anaconda3\envs\env1\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [31]:
cross_val_score(RandomForestClassifier(n_estimators=40), digits.data,digits.target)

array([0.92777778, 0.88611111, 0.96100279, 0.95264624, 0.92479109])

In [32]:
cross_val_score(SVC(), digits.data,digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])